/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Converter.DATTConverter;
import Converter.PDTBConverter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Murathan
 */
public class fileChooser extends javax.swing.JFrame {

    boolean pdtb = false;
    boolean datt = false;
    String dir = "";

    /**
     * Creates new form fileChooser
     */
    public fileChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        FileChooser_annotation = new javax.swing.JFileChooser();
        RadioButtonDATT = new javax.swing.JRadioButton();
        RadioButtonPDTB = new javax.swing.JRadioButton();
        TextField_annotation = new javax.swing.JTextField();
        TextField_text = new javax.swing.JTextField();
        Button_ChooseAnnotationFile = new javax.swing.JButton();
        Button_ChooseTextFile = new javax.swing.JButton();
        Button_run = new javax.swing.JButton();

        FileChooser_annotation.setMinimumSize(new java.awt.Dimension(590, 400));
        FileChooser_annotation.setFileSelectionMode(FileChooser_annotation.DIRECTORIES_ONLY);
        FileChooser_annotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooser_annotationActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convert and Run");

        RadioButtonDATT.setText("DATT");
        buttonGroup.add(RadioButtonDATT);
        RadioButtonDATT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonDATTActionPerformed(evt);
            }
        });

        RadioButtonPDTB.setText("PDTB");
        buttonGroup.add(RadioButtonPDTB);
        RadioButtonPDTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPDTBActionPerformed(evt);
            }
        });

        TextField_annotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_annotationActionPerformed(evt);
            }
        });

        Button_ChooseAnnotationFile.setText("Choose Annotation File");
        Button_ChooseAnnotationFile.setEnabled(false);
        Button_ChooseAnnotationFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ChooseAnnotationFileActionPerformed(evt);
            }
        });

        Button_ChooseTextFile.setText("Choose Text File");
        Button_ChooseTextFile.setEnabled(false);
        Button_ChooseTextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ChooseTextFileActionPerformed(evt);
            }
        });

        Button_run.setText("RUN");
        Button_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_runActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 172, Short.MAX_VALUE)
                        .addComponent(RadioButtonDATT)
                        .addGap(33, 33, 33)
                        .addComponent(RadioButtonPDTB)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextField_text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_annotation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_ChooseAnnotationFile)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Button_ChooseTextFile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Button_run)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_annotation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_ChooseAnnotationFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_ChooseTextFile))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonPDTB)
                    .addComponent(RadioButtonDATT)
                    .addComponent(Button_run))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ChooseAnnotationFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChooseAnnotationFileActionPerformed
        // TODO add your handling code here:
        int status = FileChooser_annotation.showOpenDialog(null);

        if (status == FileChooser_annotation.APPROVE_OPTION) {
            File selectedFile = FileChooser_annotation.getSelectedFile();
            TextField_annotation.setText(selectedFile.getAbsolutePath());
            System.out.println("n: " + selectedFile.getAbsolutePath());
        } else if (status == FileChooser_annotation.CANCEL_OPTION) {
            System.out.println("canceled");
        }

    }//GEN-LAST:event_Button_ChooseAnnotationFileActionPerformed

    private void RadioButtonPDTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPDTBActionPerformed
        // TODO add your handling code here:
        Button_ChooseTextFile.setVisible(true);
        TextField_text.setVisible(true);
        Button_ChooseAnnotationFile.setEnabled(true);
        Button_ChooseTextFile.setEnabled(true);
    }//GEN-LAST:event_RadioButtonPDTBActionPerformed

    private void RadioButtonDATTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonDATTActionPerformed
        // TODO add your handling code here:
        Button_ChooseTextFile.setVisible(false);
        TextField_text.setVisible(false);
        Button_ChooseAnnotationFile.setEnabled(true);
        // Button_ChooseTextFile.setEnabled(true);

    }//GEN-LAST:event_RadioButtonDATTActionPerformed

    private void FileChooser_annotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooser_annotationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FileChooser_annotationActionPerformed

    private void Button_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_runActionPerformed
        // TODO add your handling code here:

        if (RadioButtonDATT.isSelected()) {
            try {
                System.out.println("Selected::: " + TextField_annotation.getText());
                DATTConverter converterDATT = new DATTConverter(TextField_annotation.getText(), TextField_text.getText());
                dir = converterDATT.getOutputDir();
            } catch (ParserConfigurationException | SAXException | IOException ex) {
                Logger.getLogger(fileChooser.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (RadioButtonPDTB.isSelected()) {

            try {
                PDTBConverter converterPDTB = new PDTBConverter(TextField_annotation.getText(), TextField_text.getText(), "testing_pdtb.xml");
                dir = converterPDTB.getOutputDir();

            } catch (IOException ex) {
                Logger.getLogger(fileChooser.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        this.dispose();
        try {
            new MainWindow(dir).setVisible(true);
        } catch (IOException | SAXException | ParserConfigurationException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_runActionPerformed

    private void Button_ChooseTextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChooseTextFileActionPerformed
        // TODO add your handling code here:
        int status = FileChooser_annotation.showOpenDialog(null);

        if (status == FileChooser_annotation.APPROVE_OPTION) {
            File selectedFile = FileChooser_annotation.getSelectedFile();
            TextField_text.setText(selectedFile.getAbsolutePath());
            System.out.println("n: " + selectedFile.getAbsolutePath());
        } else if (status == FileChooser_annotation.CANCEL_OPTION) {
            System.out.println("canceled");
        }
    }//GEN-LAST:event_Button_ChooseTextFileActionPerformed

    private void TextField_annotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_annotationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_annotationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fileChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ChooseAnnotationFile;
    private javax.swing.JButton Button_ChooseTextFile;
    private javax.swing.JButton Button_run;
    private javax.swing.JFileChooser FileChooser_annotation;
    private javax.swing.JRadioButton RadioButtonDATT;
    private javax.swing.JRadioButton RadioButtonPDTB;
    private javax.swing.JTextField TextField_annotation;
    private javax.swing.JTextField TextField_text;
    private javax.swing.ButtonGroup buttonGroup;
    // End of variables declaration//GEN-END:variables
}
